***Settings***
Documentation        objetos logout


*** Variables ***
&{options_logout}
...            inc_logout=incLogout.png
...            tela_deseja_realizar_logout=telaDesejaLogout.png
...            btn_sim=btnSimLogout.png
...            tela_Planos=telaPlanos.png
...            btn_cancelar_tl_Planos=btnCancelarTPlanos.png
...            inc_logout_minimizado=incLogoutMinimizado.png    